# Generated by Django 3.2.3 on 2021-06-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
    ]
