# Generated by Django 3.2.3 on 2021-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20210612_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/'),
        ),
    ]
