# Generated by Django 3.2.3 on 2021-06-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='myuser',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image_url',
            field=models.CharField(default='https://microddit-api.herokuapp.com/media/uploads/default.png', max_length=350),
        ),
    ]
